# Generated by Django 5.0.2 on 2024-03-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_classes_enrollments_parents_profiles_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='student1',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='student2',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='student3',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='teacher',
        ),
    ]
