# Generated by Django 5.0.2 on 2024-03-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
