# Generated by Django 5.0.2 on 2024-03-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
