# Generated by Django 5.0.2 on 2024-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_teacher'),
    ]

    operations = [

    ]
