# Generated by Django 5.0.2 on 2024-03-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_classes_classroom_parents_schedule_student_teacher_and_more'),
    ]

    operations = [

    ]
