# Generated by Django 5.0.2 on 2024-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_classes_student1_remove_classes_student2_and_more'),
    ]

    operations = [


    ]
