# Generated by Django 5.0.2 on 2024-03-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacher_users_delete_profiles_delete_zipcode_and_more'),
        ('main', '0007_delete_profiles'),
    ]

    operations = [
    ]
