# Generated by Django 5.0.2 on 2024-03-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_student_remove_classes_student1_and_more'),
    ]

    operations = [

    ]
