# Generated by Django 5.0.2 on 2024-03-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_enrollments'),
    ]

    operations = [
    ]
