# Generated by Django 5.0.2 on 2024-03-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_classes_delete_classroom_delete_parents_and_more'),
    ]

    operations = [
    ]
