# Generated by Django 5.0.2 on 2024-08-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_student_under_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='student',
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
