# Generated by Django 5.0.2 on 2024-10-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_teacher_email_alter_teacher_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
