# Generated by Django 5.0.2 on 2024-11-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_teacher_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
