# Generated by Django 5.0.2 on 2024-11-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_teacher_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.classes'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student'),
        ),
    ]
