# Generated by Django 5.0.2 on 2024-11-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_schedule_student_alter_student_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parents'),
        ),
    ]
