# Generated by Django 5.0.2 on 2024-11-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_student_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
