# Generated by Django 5.0.2 on 2024-11-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_enrollments_classname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
    ]
