# Generated by Django 5.0.2 on 2024-11-03 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_student_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.parents'),
            preserve_default=False,
        ),
    ]
