# Generated by Django 5.0.2 on 2024-11-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_student_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='student',
        ),
    ]
