# Generated by Django 5.0.2 on 2024-11-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_schedule_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollments',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parents',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.users'),
            preserve_default=False,
        ),
    ]
