# Generated by Django 5.0.2 on 2024-11-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_classes_author_classroom_author_enrollments_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
