# Generated by Django 5.0.2 on 2024-11-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='author',
        ),
        migrations.AddField(
            model_name='classes',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
