# Generated by Django 5.0.2 on 2024-11-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_classes_author_classes_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='author',
        ),
        migrations.RemoveField(
            model_name='enrollments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='author',
        ),
        migrations.RemoveField(
            model_name='student',
            name='author',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='author',
        ),
        migrations.AddField(
            model_name='classroom',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollments',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parents',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
