# Generated by Django 5.0.2 on 2024-11-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_student_parents_student_email_guardian_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
