# Generated by Django 5.0.2 on 2024-11-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_delete_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='classname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classes'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student'),
        ),
    ]
